---
services:
  php-cli:
    build:
        context: .
        args:
          - HOST_UID=${HOST_UID:-1000}
    container_name: "phpcli-huawei-sms"
    user: www
    command: sh -c "composer update && php index.php"
#    command: sh -c "ls -lah /var/www/html"
    volumes:
      - ../:/var/www/html
      - ./docker-oc-php.ini:/usr/local/etc/php/conf.d/docker-oc-php.ini
